<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Aset_lancar extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        if(!isset($_SESSION)){
            session_start();
        }
        if (!isset($_SESSION['id_user'])) {
            redirect(base_url());
        }
        $this->load->model('Aset_lancar_model');
    } 

    /*
     * Listing of aset_lancar
     */
    function index()
    {
        $data['nama']       = $_SESSION['nama'];
        $data['id_user']    = $_SESSION['id_user'];
        $data['aset_lancar'] = $this->Aset_lancar_model->get_all_aset_lancar();
        
        $data['_view'] = 'aset_lancar/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new aset_lancar
     */
    function add()
    {   
        $data['nama']       = $_SESSION['nama'];
        $data['id_user']    = $_SESSION['id_user'];
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'jenis' => $this->input->post('jenis'),
				'jumlah' => $this->input->post('jumlah'),
				'nilai' => $this->input->post('nilai'),
				'total' => $this->input->post('total'),
                'keterangan' => $this->input->post('keterangan'),
            );
            
            $aset_lancar_id = $this->Aset_lancar_model->add_aset_lancar($params);
            redirect('aset_lancar/index');
        }
        else
        {            
            $data['_view'] = 'aset_lancar/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a aset_lancar
     */
    function edit($id_aset_lancar)
    {   
        // check if the aset_lancar exists before trying to edit it
        $data['nama']       = $_SESSION['nama'];
        $data['id_user']    = $_SESSION['id_user'];
        $data['aset_lancar'] = $this->Aset_lancar_model->get_aset_lancar($id_aset_lancar);
        
        if(isset($data['aset_lancar']['id_aset_lancar']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'jenis' => $this->input->post('jenis'),
					'jumlah' => $this->input->post('jumlah'),
					'nilai' => $this->input->post('nilai'),
					'total' => $this->input->post('total'),
                    'keterangan' => $this->input->post('keterangan'),
                );

                $this->Aset_lancar_model->update_aset_lancar($id_aset_lancar,$params);            
                redirect('aset_lancar/index');
            }
            else
            {
                $data['_view'] = 'aset_lancar/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The aset_lancar you are trying to edit does not exist.');
    } 

    /*
     * Deleting aset_lancar
     */
    function remove($id_aset_lancar)
    {
        $aset_lancar = $this->Aset_lancar_model->get_aset_lancar($id_aset_lancar);

        // check if the aset_lancar exists before trying to delete it
        if(isset($aset_lancar['id_aset_lancar']))
        {
            $this->Aset_lancar_model->delete_aset_lancar($id_aset_lancar);
            redirect('aset_lancar/index');
        }
        else
            show_error('The aset_lancar you are trying to delete does not exist.');
    }
    
}
