<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Aset_tetap extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        if(!isset($_SESSION)){
            session_start();
        }
        if (!isset($_SESSION['id_user'])) {
            redirect(base_url());
        }
        $this->load->model('Aset_tetap_model');
    } 

    /*
     * Listing of aset_tetap
     */
    function index()
    {
        $data['nama']       = $_SESSION['nama'];
        $data['id_user']    = $_SESSION['id_user'];
        //$data['aset_tetap'] = $this->Aset_tetap_model->get_all_aset_tetap();
        
        $data['_view'] = 'aset_tetap/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new aset_tetap
     */
    function add()
    {   
        $data['nama']       = $_SESSION['nama'];
        $data['id_user']    = $_SESSION['id_user'];
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $nilai          = $this->input->post('nilai');
            $jenis          = $this->input->post('jenis');
            $lama_dimiliki  = $this->input->post('lama_dimiliki');
    
            if ($jenis=="Bangunan") {
                if ($lama_dimiliki>=1) {
                    $penyusutan = $nilai/20;
                }elseif ($lama_dimiliki==0) {
                    $penyusutan = 0;
                }
            }elseif ($jenis=="Non Bangunan") {
                if ($lama_dimiliki>=1) {
                    $penyusutan = $nilai/5;
                }elseif ($lama_dimiliki==0) {
                    $penyusutan = 0;
                }
            }

            if ($jenis=="Bangunan"&&$lama_dimiliki>=20){
            $akumulasi = $penyusutan*1;
            } elseif ($jenis=="Non Bangunan"&&$lama_dimiliki>=5) {
            $akumulasi = $penyusutan*1;
            }else{
             $akumulasi = $penyusutan*$lama_dimiliki;   
            }
            
            $params = array(
				'jenis' => $jenis,
				'tanggal' => $this->input->post('tanggal'),
				'nilai' => $nilai,
				'lama_dimiliki' => $lama_dimiliki,
                'keterangan' => $this->input->post('keterangan'),
                'penyusutan' => $penyusutan,
                'akumulasi' => $akumulasi,
                'id_user' => $this->input->post('id_user'),
            );
            
            $aset_tetap_id = $this->Aset_tetap_model->add_aset_tetap($params);
            redirect('aset_tetap/index');
        }
        else
        {            
            $data['_view'] = 'aset_tetap/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a aset_tetap
     */
    function edit($id_aset_tetap)
    {   
        // check if the aset_tetap exists before trying to edit it
        $data['nama']       = $_SESSION['nama'];
        $data['id_user']    = $_SESSION['id_user'];
        $data['aset_tetap'] = $this->Aset_tetap_model->get_aset_tetap($id_aset_tetap);
        
        if(isset($data['aset_tetap']['id_aset_tetap']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $nilai          = $this->input->post('nilai');
                $jenis          = $this->input->post('jenis');
                $lama_dimiliki  = $this->input->post('lama_dimiliki');
        
                if ($jenis=="Bangunan") {
                $penyusutan = $nilai/20;
                }else{
                $penyusutan = $nilai/5;
                }

                if ($jenis=="Bangunan"&&$lama_dimiliki>=20){
                $akumulasi = $penyusutan*1;
                } elseif ($jenis=="Non Bangunan"&&$lama_dimiliki>=5) {
                $akumulasi = $penyusutan*1;
                }else{
                 $akumulasi = $penyusutan*$lama_dimiliki;   
            }
                $params = array(
    				'jenis' => $jenis,
                    'tanggal' => $this->input->post('tanggal'),
                    'nilai' => $nilai,
                    'lama_dimiliki' => $lama_dimiliki,
                    'keterangan' => $this->input->post('keterangan'),
                    'penyusutan' => $penyusutan,
                    'akumulasi' => $akumulasi,
                    'id_user' => $this->input->post('id_user'),
                );

                $this->Aset_tetap_model->update_aset_tetap($id_aset_tetap,$params);            
                redirect('aset_tetap/index');
            }
            else
            {
                $data['_view'] = 'aset_tetap/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The aset_tetap you are trying to edit does not exist.');
    } 

    /*
     * Deleting aset_tetap
     */
    function remove($id_aset_tetap)
    {
        $aset_tetap = $this->Aset_tetap_model->get_aset_tetap($id_aset_tetap);

        // check if the aset_tetap exists before trying to delete it
        if(isset($aset_tetap['id_aset_tetap']))
        {
            $this->Aset_tetap_model->delete_aset_tetap($id_aset_tetap);
            redirect('aset_tetap/index');
        }
        else
            show_error('The aset_tetap you are trying to delete does not exist.');
    }
    
}
