<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    public function __construct()
    {
       parent::__construct();
         if(!isset($_SESSION)){
            session_start();
        }
        if (!isset($_SESSION['id_user'])) {
            redirect(base_url());
        }
        
    }

    public function index()
    {
        $data['nama']       = $_SESSION['nama'];
        $data['id_user']    = $_SESSION['id_user'];
        $data['email']      = $_SESSION['username'];
        $data['_view'] = 'dashboard';
        $this->load->view('layouts/main',$data);
    }

    public function dash(){
    	$data['_view'] = 'dashboard';
        $data['nama']       = $_SESSION['nama'];
        $data['id_user']    = $_SESSION['id_user'];
        $data['email']      = $_SESSION['username'];
        $this->load->view('layouts/main',$data);
    }

    public function logout(){
        session_destroy();
        redirect(base_url());
    }
}
