<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Modal extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        if(!isset($_SESSION)){
            session_start();
        }
        if (!isset($_SESSION['id_user'])) {
            redirect(base_url());
        }
        $this->load->model('Modal_model');
    } 

    /*
     * Listing of modal
     */
    function index()
    {
        $data['nama']       = $_SESSION['nama'];
        $data['id_user']    = $_SESSION['id_user'];
        $data['modal'] = $this->Modal_model->get_all_modal();
        
        $data['_view'] = 'modal/index';
        $this->load->view('layouts/main',$data);
    }

    function showPenambahan()
    {
        $data['nama']       = $_SESSION['nama'];
        $data['id_user']    = $_SESSION['id_user'];
        //$data['modal'] = $this->Modal_model->get_penambahan_modal();
        
        $data['_view'] = 'modal/penambahan';
        $this->load->view('layouts/main',$data);
    }

    function showPengurangan()
    {
        $data['nama']       = $_SESSION['nama'];
        $data['id_user']    = $_SESSION['id_user'];
        //$data['modal'] = $this->Modal_model->get_pengurangan_modal();
        
        $data['_view'] = 'modal/pengurangan';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new modal
     */
    function add()
    {   
        $data['nama']       = $_SESSION['nama'];
        $data['id_user']    = $_SESSION['id_user'];
        $status             = $this->input->post('status');
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'tanggal' => $this->input->post('tanggal'),
				'keterangan' => $this->input->post('keterangan'),
				'jumlah' => $this->input->post('jumlah'),
                'status' => $this->input->post('status'),
                'id_user' => $this->input->post('id_user'),
            );
            
            $modal_id = $this->Modal_model->add_modal($params);
            if ($status=='Penambahan') {
                redirect('modal/showPenambahan');
            }else{
                redirect('modal/showPengurangan');
            }
            
        }
        else
        {            
            $data['_view'] = 'modal/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a modal
     */
    function edit($id_modal)
    {   
        // check if the modal exists before trying to edit it
        $data['nama']       = $_SESSION['nama'];
        $data['id_user']    = $_SESSION['id_user'];
        $data['modal'] = $this->Modal_model->get_modal($id_modal);
        $status             = $this->input->post('status');
        
        if(isset($data['modal']['id_modal']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'tanggal' => $this->input->post('tanggal'),
					'keterangan' => $this->input->post('keterangan'),
					'jumlah' => $this->input->post('jumlah'),
                    'status' => $this->input->post('status'),
                    'id_user' => $this->input->post('id_user'),
                );

                $this->Modal_model->update_modal($id_modal,$params);            
                if ($status=='Penambahan') {
                redirect('modal/showPenambahan');
                }else{
                    redirect('modal/showPengurangan');
                }
            }
            else
            {
                $data['_view'] = 'modal/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The modal you are trying to edit does not exist.');
    } 

    /*
     * Deleting modal
     */
    function remove($id_modal)
    {
        $modal = $this->Modal_model->get_modal($id_modal);

        // check if the modal exists before trying to delete it
        if(isset($modal['id_modal']))
        {
            $this->Modal_model->delete_modal($id_modal);
            redirect('dashboard');
        }
        else
            show_error('The modal you are trying to delete does not exist.');
    }
    
}
