<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pengeluaran extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        if(!isset($_SESSION)){
            session_start();
        }
        if (!isset($_SESSION['id_user'])) {
            redirect(base_url());
        }
        $this->load->model('Pengeluaran_model');
    } 

    /*
     * Listing of pengeluaran
     */
    function index()
    {
        $data['nama']       = $_SESSION['nama'];
        $data['id_user']    = $_SESSION['id_user'];
        $data['email']      = $_SESSION['username'];
        //$data['pengeluaran'] = $this->Pengeluaran_model->get_all_pengeluaran();
        
        $data['_view'] = 'pengeluaran/index';
        $this->load->view('layouts/main',$data);
    }

    function showHutang()
    {
        $data['nama']       = $_SESSION['nama'];
        $data['id_user']    = $_SESSION['id_user'];
        $data['email']      = $_SESSION['username'];
        //$data['pengeluaran'] = $this->Pengeluaran_model->get_hutang();
        
        $data['_view'] = 'pengeluaran/hutang';
        $this->load->view('layouts/main',$data);
    }

    function showHutangLain()
    {
        $data['nama']       = $_SESSION['nama'];
        $data['id_user']    = $_SESSION['id_user'];
        $data['email']      = $_SESSION['username'];
        //$data['pengeluaran'] = $this->Pengeluaran_model->get_hutanglain();
        
        $data['_view'] = 'pengeluaran/hutanglain';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new pengeluaran
     */
    function add()
    {   
        $data['nama']       = $_SESSION['nama'];
        $data['id_user']    = $_SESSION['id_user'];
        $data['email']      = $_SESSION['username'];
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'tanggal' => $this->input->post('tanggal'),
                'tanggal_japo' => $this->input->post('tanggal_japo'),
				'produk' => $this->input->post('produk'),
				'kuantitas' => $this->input->post('kuantitas'),
				'harga_satuan' => $this->input->post('harga_satuan'),
				'total' => $this->input->post('total'),
                'status' => $this->input->post('status'),
                'jenis' => $this->input->post('jenis'),
                'keterangan' => $this->input->post('keterangan'),
                'id_user' => $this->input->post('id_user'),
            );
            
            $pengeluaran_id = $this->Pengeluaran_model->add_pengeluaran($params);
            redirect('pengeluaran/index');
        }
        else
        {            
            $data['_view'] = 'pengeluaran/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a pengeluaran
     */
    function edit($id_pengeluaran)
    {   
        $data['nama']       = $_SESSION['nama'];
        $data['id_user']    = $_SESSION['id_user'];
        $data['email']      = $_SESSION['username'];
        // check if the pengeluaran exists before trying to edit it
        $data['pengeluaran'] = $this->Pengeluaran_model->get_pengeluaran($id_pengeluaran);
        
        if(isset($data['pengeluaran']['id_pengeluaran']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'tanggal' => $this->input->post('tanggal'),
                    'tanggal_japo' => $this->input->post('tanggal_japo'),
					'produk' => $this->input->post('produk'),
					'kuantitas' => $this->input->post('kuantitas'),
					'harga_satuan' => $this->input->post('harga_satuan'),
					'total' => $this->input->post('total'),
                    'status' => $this->input->post('status'),
                    'jenis' => $this->input->post('jenis'),
                    'keterangan' => $this->input->post('keterangan'),
                    'id_user' => $this->input->post('id_user'),
                );

                $this->Pengeluaran_model->update_pengeluaran($id_pengeluaran,$params);            
                redirect('pengeluaran/index');
            }
            else
            {
                $data['_view'] = 'pengeluaran/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The pengeluaran you are trying to edit does not exist.');
    } 

    /*
     * Deleting pengeluaran
     */
    function remove($id_pengeluaran)
    {
        $pengeluaran = $this->Pengeluaran_model->get_pengeluaran($id_pengeluaran);

        // check if the pengeluaran exists before trying to delete it
        if(isset($pengeluaran['id_pengeluaran']))
        {
            $this->Pengeluaran_model->delete_pengeluaran($id_pengeluaran);
            redirect('pengeluaran/index');
        }
        else
            show_error('The pengeluaran you are trying to delete does not exist.');
    }
    
}
