<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Penjualan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        if(!isset($_SESSION)){
            session_start();
        }
        if (!isset($_SESSION['id_user'])) {
            redirect(base_url());
        }
        $this->load->model('Penjualan_model');
    } 

    /*
     * Listing of penjualan
     */
    function index()
    {
        $data['nama']       = $_SESSION['nama'];
        $data['id_user']    = $_SESSION['id_user'];
        $data['email']      = $_SESSION['username'];
        //$data['penjualan'] = $this->Penjualan_model->get_all_penjualan();
        
        $data['_view'] = 'penjualan/index';
        $this->load->view('layouts/main',$data);
    }

    function showPiutang()
    {
        $data['nama']       = $_SESSION['nama'];
        $data['id_user']    = $_SESSION['id_user'];
        $data['email']      = $_SESSION['username'];
        //$data['penjualan'] = $this->Penjualan_model->get_piutang();
        
        $data['_view'] = 'penjualan/piutang';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new penjualan
     */
    function add()
    {   
        $data['nama']       = $_SESSION['nama'];
        $data['id_user']    = $_SESSION['id_user'];
        $data['email']      = $_SESSION['username'];
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'tanggal' => $this->input->post('tanggal'),
                'tanggal_japo' => $this->input->post('tanggal_japo'),
				'produk' => $this->input->post('produk'),
				'kuantitas' => $this->input->post('kuantitas'),
				'harga_satuan' => $this->input->post('harga_satuan'),
				'total' => $this->input->post('total'),
                'status' => $this->input->post('status'),
                'keterangan' => $this->input->post('keterangan'),
                'id_user' => $this->input->post('id_user'),
            );
            
            $penjualan_id = $this->Penjualan_model->add_penjualan($params);
            redirect('penjualan/index');
        }
        else
        {            
            $data['_view'] = 'penjualan/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a penjualan
     */
    function edit($id_penjulan)
    {   
        $data['nama']       = $_SESSION['nama'];
        $data['id_user']    = $_SESSION['id_user'];
        $data['email']      = $_SESSION['username'];
        // check if the penjualan exists before trying to edit it
        $data['penjualan'] = $this->Penjualan_model->get_penjualan($id_penjulan);
        
        if(isset($data['penjualan']['id_penjulan']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'tanggal' => $this->input->post('tanggal'),
                    'tanggal_japo' => $this->input->post('tanggal_japo'),
					'produk' => $this->input->post('produk'),
					'kuantitas' => $this->input->post('kuantitas'),
					'harga_satuan' => $this->input->post('harga_satuan'),
					'total' => $this->input->post('total'),
                    'status' => $this->input->post('status'),
                    'keterangan' => $this->input->post('keterangan'),
                    'id_user' => $this->input->post('id_user'),
                );

                $this->Penjualan_model->update_penjualan($id_penjulan,$params);            
                redirect('penjualan/index');
            }
            else
            {
                $data['_view'] = 'penjualan/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The penjualan you are trying to edit does not exist.');
    } 

    /*
     * Deleting penjualan
     */
    function remove($id_penjulan)
    {
        $penjualan = $this->Penjualan_model->get_penjualan($id_penjulan);

        // check if the penjualan exists before trying to delete it
        if(isset($penjualan['id_penjulan']))
        {
            $this->Penjualan_model->delete_penjualan($id_penjulan);
            redirect('penjualan/index');
        }
        else
            show_error('The penjualan you are trying to delete does not exist.');
    }
    
}
