<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Saldo extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        if(!isset($_SESSION)){
            session_start();
        }
        if (!isset($_SESSION['id_user'])) {
            redirect(base_url());
        }
        $this->load->model('Saldo_model');
    } 

    /*
     * Listing of saldo
     */
    function index()
    {
        $data['nama']       = $_SESSION['nama'];
        $data['id_user']    = $_SESSION['id_user'];
        $data['saldo'] = $this->Saldo_model->get_all_saldo();
        
        $data['_view'] = 'saldo/edit';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new saldo
     */
    function add()
    {   
        $data['nama']       = $_SESSION['nama'];
        $data['id_user']    = $_SESSION['id_user'];
        $id_user            = $this->input->post('id_user');
        $this->Saldo_model->delete_saldo($id_user);

        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'tanggal' => $this->input->post('tanggal'),
				'produk' => $this->input->post('produk'),
				'total' => $this->input->post('total'),
                'keterangan' => $this->input->post('keterangan'),
                'id_user' => $this->input->post('id_user'),
            );
            
            $saldo_id = $this->Saldo_model->add_saldo($params);
            redirect('saldo/index');
        }
        else
        {            
            $data['_view'] = 'saldo/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a saldo
     */
    // function edit($id_saldo)
    // {   
    //     // check if the saldo exists before trying to edit it
    //     $data['nama']       = $_SESSION['nama'];
    //     $data['id_user']    = $_SESSION['id_user'];
    //     $data['saldo']      = $this->Saldo_model->get_saldo($id_saldo);
        
    //     if(isset($data['saldo']['id_saldo']))
    //     {
    //         if(isset($_POST) && count($_POST) > 0)     
    //         {   
    //             $params = array(
				// 	'tanggal' => $this->input->post('tanggal'),
				// 	'produk' => $this->input->post('produk'),
				// 	'total' => $this->input->post('total'),
    //                 'keterangan' => $this->input->post('keterangan'),
    //                 'id_user' => $this->input->post('id_user'),
    //             );

    //             $this->Saldo_model->update_saldo($id_saldo,$params);            
    //             redirect('saldo/edit/1');
    //         }
    //         else
    //         {
    //             $data['_view'] = 'saldo/edit';
    //             $this->load->view('layouts/main',$data);
    //         }
    //     }
    //     else
    //         show_error('The saldo you are trying to edit does not exist.');
    // } 

    // /*
    //  * Deleting saldo
    //  */
    // function remove($id_saldo)
    // {
    //     $saldo = $this->Saldo_model->get_saldo($id_saldo);

    //     // check if the saldo exists before trying to delete it
    //     if(isset($saldo['id_saldo']))
    //     {
    //         $this->Saldo_model->delete_saldo($id_saldo);
    //         redirect('saldo/index');
    //     }
    //     else
    //         show_error('The saldo you are trying to delete does not exist.');
    // }
    
}
