<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Aset_tetap_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get aset_tetap by id_aset_tetap
     */
    function get_aset_tetap($id_aset_tetap)
    {
        return $this->db->get_where('aset_tetap',array('id_aset_tetap'=>$id_aset_tetap))->row_array();
    }
        
    /*
     * Get all aset_tetap
     */
    function get_all_aset_tetap()
    {
        $this->db->order_by('id_aset_tetap', 'desc');
        return $this->db->get('aset_tetap')->result_array();
    }
        
    /*
     * function to add new aset_tetap
     */
    function add_aset_tetap($params)
    {
        $this->db->insert('aset_tetap',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update aset_tetap
     */
    function update_aset_tetap($id_aset_tetap,$params)
    {
        $this->db->where('id_aset_tetap',$id_aset_tetap);
        return $this->db->update('aset_tetap',$params);
    }
    
    /*
     * function to delete aset_tetap
     */
    function delete_aset_tetap($id_aset_tetap)
    {
        return $this->db->delete('aset_tetap',array('id_aset_tetap'=>$id_aset_tetap));
    }
}
