<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Aset_lancar_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get aset_lancar by id_aset_lancar
     */
    function get_aset_lancar($id_aset_lancar)
    {
        return $this->db->get_where('aset_lancar',array('id_aset_lancar'=>$id_aset_lancar))->row_array();
    }
        
    /*
     * Get all aset_lancar
     */
    function get_all_aset_lancar()
    {
        $this->db->order_by('id_aset_lancar', 'ASC');
        return $this->db->get('aset_lancar')->result_array();
    }
        
    /*
     * function to add new aset_lancar
     */
    function add_aset_lancar($params)
    {
        $this->db->insert('aset_lancar',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update aset_lancar
     */
    function update_aset_lancar($id_aset_lancar,$params)
    {
        $this->db->where('id_aset_lancar',$id_aset_lancar);
        return $this->db->update('aset_lancar',$params);
    }
    
    /*
     * function to delete aset_lancar
     */
    function delete_aset_lancar($id_aset_lancar)
    {
        return $this->db->delete('aset_lancar',array('id_aset_lancar'=>$id_aset_lancar));
    }
}
