<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Modal_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get modal by id_modal
     */
    function get_modal($id_modal)
    {
        return $this->db->get_where('modal',array('id_modal'=>$id_modal))->row_array();
    }

    
    function get_penambahan_modal()
    {
        return $this->db->get_where('modal',array('status'=>'Penambahan'))->result_array();
    }

    function get_pengurangan_modal()
    {
        return $this->db->get_where('modal',array('status'=>'Pengurangan'))->result_array();
    }

    /*
     * Get all modal
     */
    function get_all_modal()
    {
        $this->db->order_by('id_modal', 'desc');
        return $this->db->get('modal')->result_array();
    }
        
    /*
     * function to add new modal
     */
    function add_modal($params)
    {
        $this->db->insert('modal',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update modal
     */
    function update_modal($id_modal,$params)
    {
        $this->db->where('id_modal',$id_modal);
        return $this->db->update('modal',$params);
    }
    
    /*
     * function to delete modal
     */
    function delete_modal($id_modal)
    {
        return $this->db->delete('modal',array('id_modal'=>$id_modal));
    }
}
