<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pembelian_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pembelian by id_pembelian
     */
    function get_pembelian($id_pembelian)
    {
        return $this->db->get_where('pembelian',array('id_pembelian'=>$id_pembelian))->row_array();
    }
        
    /*
     * Get all pembelian
     */
    function get_all_pembelian()
    {
        $this->db->order_by('id_pembelian', 'desc');
        return $this->db->get('pembelian')->result_array();
    }
        
    /*
     * function to add new pembelian
     */
    function add_pembelian($params)
    {
        $this->db->insert('pembelian',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pembelian
     */
    function update_pembelian($id_pembelian,$params)
    {
        $this->db->where('id_pembelian',$id_pembelian);
        return $this->db->update('pembelian',$params);
    }
    
    /*
     * function to delete pembelian
     */
    function delete_pembelian($id_pembelian)
    {
        return $this->db->delete('pembelian',array('id_pembelian'=>$id_pembelian));
    }
}
