<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pengeluaran_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pengeluaran by id_pengeluaran
     */
    function get_pengeluaran($id_pengeluaran)
    {
        return $this->db->get_where('pengeluaran',array('id_pengeluaran'=>$id_pengeluaran))->row_array();
    }

    function get_hutang()
    {
        return $this->db->get_where('pengeluaran',array('status'=>'Belum Lunas'))->result_array();
    }

    function get_hutanglain()
    {
        return $this->db->get_where('pengeluaran',array('status'=>'Belum Lunas','jenis'=>'Lain-Lain'))->result_array();
    }
        
    /*
     * Get all pengeluaran
     */
    function get_all_pengeluaran()
    {
        $this->db->order_by('id_pengeluaran', 'desc');
        return $this->db->get('pengeluaran')->result_array();
    }
        
    /*
     * function to add new pengeluaran
     */
    function add_pengeluaran($params)
    {
        $this->db->insert('pengeluaran',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pengeluaran
     */
    function update_pengeluaran($id_pengeluaran,$params)
    {
        $this->db->where('id_pengeluaran',$id_pengeluaran);
        return $this->db->update('pengeluaran',$params);
    }
    
    /*
     * function to delete pengeluaran
     */
    function delete_pengeluaran($id_pengeluaran)
    {
        return $this->db->delete('pengeluaran',array('id_pengeluaran'=>$id_pengeluaran));
    }
}
