<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Saldo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get saldo by id_saldo
     */
    function get_saldo($id_saldo)
    {
        return $this->db->get_where('saldo',array('id_saldo'=>$id_saldo))->row_array();
    }
        
    /*
     * Get all saldo
     */
    function get_all_saldo()
    {
        $this->db->order_by('id_saldo', 'desc');
        return $this->db->get('saldo')->result_array();
    }
        
    /*
     * function to add new saldo
     */
    function add_saldo($params)
    {
        $this->db->insert('saldo',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update saldo
     */
    function update_saldo($id_saldo,$params)
    {
        $this->db->where('id_saldo',$id_saldo);
        return $this->db->update('saldo',$params);
    }
    
    /*
     * function to delete saldo
     */
    function delete_saldo($id_user)
    {
        return $this->db->delete('saldo',array('id_user'=>$id_user));
    }
}
